In [3]:
import numpy as np

In [4]:
x = np.array([2,3,4,5])

In [5]:
x.itemsize

8

In [6]:
x = np.array([(2,3,4),(5,6,7)])

In [7]:
x[0:,0]

array([2, 5])

In [8]:
x.max()

7

In [9]:
x.min()

2

In [10]:
z = np.linspace(1, 100)

In [11]:
z

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [12]:
a = np.array([(1,2,3,4), (5,6,7,8), (9,0,9,0)])

In [13]:
b = np.array([(1,2,3,4), (5,6,7,8), (9,0,9,0)])

In [14]:
a+b

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18,  0, 18,  0]])

In [15]:
a.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 9, 0])

In [16]:
(a+b).ravel()

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18,  0, 18,  0])

In [17]:
(a+b).sum(axis = 1)

array([20, 52, 36])

In [18]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 0.        , 3.        , 0.        ]])

In [19]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 1.00000000e+00, 8.10308393e+03, 1.00000000e+00]])

In [20]:
np.log(b)

/tmp/ipykernel_234770/4200754868.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(b)


array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458,       -inf, 2.19722458,       -inf]])

In [21]:
np.random.randint(0,10)

4