In [1]:
import numpy as np

In [5]:
np_sqrt = np.sqrt([16, 25])

In [6]:
np_sqrt

array([4., 5.])

In [13]:
from numpy import pi
np.cos(0)

1.0

In [14]:
np.cos(4)

-0.6536436208636119

In [15]:
np.sin(1)

0.8414709848078965

In [16]:
np.cos(pi)

-1.0

In [17]:
np.sin(pi/2)

1.0

In [18]:
np.cos(pi)

-1.0

In [19]:
array = np.array([1,2,3,4])

In [20]:
array

array([1, 2, 3, 4])

In [23]:
x = np.zeros([5,5])

In [24]:
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
y = np.ones([4,4])

In [26]:
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
z = np.empty([3,3])

In [28]:
z

array([[7.76532116e-317, 0.00000000e+000, 2.44029516e-312],
       [1.01855798e-312, 6.79243019e+199, 4.27255602e+180],
       [7.49778978e+247, 7.34629039e+223, 3.95252517e-322]])

In [30]:
a = np.arange(15)

In [31]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
a = np.linspace(1,10,5)

In [35]:
a

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [38]:
TwoD_array = np.arange(12).reshape(4,3)

In [39]:
TwoD_array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [40]:
ThreeD_array = np.arange(27).reshape(3,3,3)

In [41]:
ThreeD_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [43]:
t = np.arange(125).reshape(5,5,5)

In [44]:
t

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24]],

       [[ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49]],

       [[ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124]]])

In [51]:
a = np.array(([2,3,4],[4,5,6]))

In [55]:
a

array([[2, 3, 4],
       [4, 5, 6]])

In [52]:
b = np.array(([5,6,7],[8,9,0]))

In [56]:
b

array([[5, 6, 7],
       [8, 9, 0]])

In [53]:
c = np.add(a, b)

In [54]:
c

array([[ 7,  9, 11],
       [12, 14,  6]])

In [58]:
d = np.subtract(a,b)

In [59]:
d

array([[-3, -3, -3],
       [-4, -4,  6]])

In [60]:
np.power(a,b)

array([[     32,     729,   16384],
       [  65536, 1953125,       1]])

In [61]:
np.power(b,a)

array([[   25,   216,  2401],
       [ 4096, 59049,     0]])

In [64]:
x = np.array([i for i in range(12)])

In [65]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [66]:
np.where(x%2==0, 'Even', 'Odd')

array(['Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even',
       'Odd', 'Even', 'Odd'], dtype='<U4')

In [67]:
condlist = (x<5, x>5)
choicelist = (x**2, x**3)

In [68]:
np.select(condlist, choicelist, default = x)

array([   0,    1,    4,    9,   16,    5,  216,  343,  512,  729, 1000,
       1331])

In [70]:
 v = np.array((([1,2,3],[4,5,6],[7,8,9])))

In [71]:
v

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
np.min(v)

1

In [73]:
np.min(v, axis = 0)

array([1, 2, 3])

In [74]:
np.min(v, axis=1)

array([1, 4, 7])

In [75]:
np.max(v)

9

In [76]:
np.mean(v)

5.0

In [77]:
np.std(v)

2.581988897471611

In [78]:
np.var(v)

6.666666666666667

In [81]:
np.percentile(v, 25)

3.0

In [82]:
np.floor(v)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [83]:
np.ceil(v)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])